apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
spec:
  secretStoreRef:
    name: homelab
    kind: ClusterSecretStore
  refreshInterval: "8760h" # Once each year, pretty static secrets. Will manually decrease secret when i need it to refresh.
  target:
    name: cloudflare-api-token-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: api_token
    remoteRef:
      key: homelab-cloudflare
      property: cloudflare_certmanager_token
