app:
  image:
    repository: linuxserver/sonarr
    tag: latest
    pullPolicy: Always

  tolerations:
    - key: "workload"
      operator: "Exists"
      value: "public"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: workload
              operator: In
              values:
                - public

  annotations:
    keel.sh/policy: "all"
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 168h"

  persistentVolumes:
    static:
      - name: config
        mountPath: /config
    hostPath:
      - name: media
        mountPath: /media/shared
        hostPath: /media/shared

  environmentVariables:
    PUID: 1000
    PGID: 1000
    TZ: Europe/Oslo

  containerPorts:
    - name: http
      containerPort: 8989
      protocol: TCP

  services:
    - name: http
      type: ClusterIP
      ports:
        - name: http
          port: 8989
          targetPort: 8989

  ingresses:
    enabled: true
    ingress:
      - name: frontend
        service:
          name: http
          port: 8989
        hosts:
          - host: sonarr.fmlab.no
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: sonarr
            hosts:
              - sonarr.fmlab.no
