---
- hosts: all
  become: true
  max_fail_percentage: 0

  tasks:
    - name: apt - update & upgrade packages
      apt:
        upgrade: full
        update_cache: yes
      register: package_upgrade

    - name: system - reboot (kernel update)
      reboot:
      when: package_upgrade.changed

    # Reboot should take place after configuring static ips in 1-config.yml
    # Else we will be stuck with no IP configuration
    - name: apt - remove packages
      apt:
        name: "{{ packages }}"
        state: absent
        autoremove: true
        purge: true
      vars:
        packages:
          - containerd
          - dhcpcd5
          - docker
          - docker-engine
          - docker.io
          - fake-hwclock
          - ifupdown
          - isc-dhcp-client
          - isc-dhcp-common
          - openresolv
          - runc

    - name: apt - install misc packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - ca-certificates
          - curl
          - gnupg
          - htop
          - nfs-kernel-server
          - ntp
          - nut
          - ufw
          - unattended-upgrades
