---
- hosts: k3s_server, k3s_agent
  become: true

  tasks:
    - name: k3s - cat node token
      command: cat /var/lib/rancher/k3s/server/node-token
      when: "'k3s_server' in group_names"
      register: k3s_node_token

    - set_fact:
        k3s_node_token: "{{ k3s_node_token.stdout }}"
      when: "'k3s_server' in group_names"

    - name: k3s - nuke agent
      shell: /usr/local/bin/k3s-agent-uninstall.sh
      ignore_errors: true
      when: "'k3s_agent' in group_names"

    - name: k3s - create cluster configuration file
      copy:
        dest: ~/k3s-agent-config.yml
        content: "{{ content }}"
      become_user: fredrick
      vars:
        content: |
          kubelet-arg: "allowed-unsafe-sysctls=net.ipv4.ip_forward,net.ipv4.conf.all.src_valid_mark"
          node-label: "workload=public"
          node-taint: "workload=public:NoSchedule"
      when: "'k3s_agent' in group_names"

    - name: k3s - join cluster
      shell: curl -sfL https://get.k3s.io | K3S_CONFIG_FILE=/home/fredrick/k3s-agent-config.yml K3S_URL=https://10.2.0.10:6443 K3S_TOKEN="{{ hostvars['srv-rpi-01']['k3s_node_token'] }}" sh -
      register: k3s_node_enroll
      when: "'k3s_agent' in group_names"

    - name: kubadm - cluster creation output
      debug:
        msg: "{{ k3s_node_enroll.stdout_lines }}"
      when: "'k3s_agent' in group_names"
