---
- hosts: k3s_server, k3s_agent
  become: true

  tasks:
    - name: system - rebooting worker nodes (cluster created)
      reboot:
      when: "'k3s_agent' in group_names"

    - name: ansible - sleep for 10 seconds
      wait_for:
        timeout: 10

    - name: system - rebooting controller nodes (cluster created)
      reboot:
      when: "'k3s_server' in group_names"
