---
- hosts: all
  become: true

  tasks:
    - name: apt - update & upgrade packages
      apt:
        upgrade: full
        update_cache: yes
        cache_valid_time: 3600
      register: package_upgrade

    - name: system - reboot (kernel update)
      reboot:
      when: package_upgrade.changed

    - name: apt - install misc packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - curl
          - htop
          - nut
          - ufw
