apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/rancher/system-upgrade-controller/v0.10.0/manifests/system-upgrade-controller.yaml
  - manifests/plan-server.yaml
  - manifests/plan-agent.yaml

images:
  - name: rancher/system-upgrade-controller
    newTag: v0.10.0
