app:
  image:
    repository: oznu/cloudflare-ddns
    tag: latest

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - srv-rpi-01

  environmentVariables:
    ZONE: "fmlab.no"
    SUBDOMAIN: "vpn"
    CRON: "* */1 * * *"

  secretEnvironmentVariables:
    - name: API_KEY
      secret:
        name: cloudflare-credentials
        key: cloudflare_ddns_token
