cert-manager:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - srv-rpi-01
  installCRDs: true
  prometheus:
    enabled: false
    servicemonitor:
      enabled: false
  clusterResourceNamespace: cert-manager
  extraArgs:
    - --cluster-resource-namespace=cert-manager
